name: medication_reminder
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.1.3+1
  http: ^0.13.4
  path_provider: ^2.0.9
  dio: ^4.0.4
  percent_indicator: ^4.0.0
  webview_flutter: ^3.0.2
  font_awesome_flutter: ^10.1.0
  get: ^4.3.8
  get_storage: ^2.0.3
  intl: ^0.17.0
  url_launcher: ^6.0.15
  share: ^2.0.4
  sizer: ^2.0.15
  package_info: ^2.0.2
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.9
  sqflite: ^2.0.2
  path: ^1.8.0
  flutter_svg: ^1.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/form
    - assets/ic_launcher.png


flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove

  color: "#E3EBEC"
  image: assets/ic_launcher.png
  color_dark: "#212230"
  image_dark: assets/ic_launcher.png
  android_gravity: center
  fullscreen: true